paylapnext-217, 218, 220 & 229
PaylinePaymentMethod/payment-method-natixis pull request #2
Opened 2020-03-26 14:56 UTC by JanFLORENT

* PAYLAPMEXT-217 gestion des certificats
* PAYLAPMEXT-220 ajout de la fonctionnalité Wallet
* PAYLAPMEXT-218 batch de récupération de la liste des banques
* PAYLAPMEXT-229 mise a jour des libs

2020-06-24 14:12 UTC, pesublet requested changes

2020-06-24 14:12 UTC, pesublet commented on src/main/java/com/payline/payment/natixis/service/GenericPaymentService.java
> +        NumberFormat nf = NumberFormat.getInstance(Locale.UK);
c'est normal cette locale UK ?

2020-06-24 14:12 UTC, pesublet commented on src/main/java/com/payline/payment/natixis/service/GenericPaymentService.java
> +        NumberFormat nf = NumberFormat.getInstance(Locale.UK);
est-ce normal la locale UK ?

2020-06-24 14:12 UTC, pesublet commented on src/main/java/com/payline/payment/natixis/service/GenericPaymentService.java
> +                builder.addAddressLine(PluginUtils.replaceChars(address.getStreet1() + " " + address.getStreet2()));
attention aux nullpointer, street1 et street2 ne sont peut être pas renseignés à chaque fois

2020-06-24 14:12 UTC, pesublet commented on src/main/java/com/payline/payment/natixis/service/GenericPaymentService.java
> +            paymentResponse = e.toPaymentResponseFailureBuilder().build();
logger l'exception ?

2020-06-24 14:12 UTC, pesublet commented on src/test/java/com/payline/payment/natixis/service/GenericPaymentServiceTest.java
> +        TestUtils.checkPaymentResponse( (PaymentResponseRedirect) paymentResponse );
tester le contenu de l'objet !

2020-06-24 14:12 UTC, pesublet commented on src/test/java/com/payline/payment/natixis/service/GenericPaymentServiceTest.java
> +        TestUtils.checkPaymentResponse( (PaymentResponseFailure) paymentResponse );
tester le contenu de l'objet !

2020-06-24 14:12 UTC, pesublet commented on src/test/java/com/payline/payment/natixis/service/GenericPaymentServiceTest.java
> +        TestUtils.checkPaymentResponse( (PaymentResponseFailure) paymentResponse );
tester le contenu de l'objet !

2020-06-24 14:12 UTC, pesublet commented on src/test/java/com/payline/payment/natixis/service/GenericPaymentServiceTest.java
> +        TestUtils.checkPaymentResponse( (PaymentResponseFailure) paymentResponse );
tester le contenu de l'objet !

2020-06-24 14:12 UTC, pesublet commented on src/test/java/com/payline/payment/natixis/service/impl/PaymentWalletServiceImplTest.java
> +        assertEquals( PaymentResponseRedirect.class, paymentResponse.getClass() );
tester le contenu de l'objet !

2020-06-24 14:12 UTC, pesublet commented on src/test/java/com/payline/payment/natixis/service/impl/PaymentWalletServiceImplTest.java
> +        assertEquals( PaymentResponseFailure.class, paymentResponse.getClass() );
tester le contenu de l'objet !

2020-06-24 14:12 UTC, pesublet commented on src/test/java/com/payline/payment/natixis/service/impl/WalletServiceImplTest.java
> +        Assertions.assertEquals(WalletCreateResponseFailure.class, response.getClass());
tester le contenu de l'objet !

2020-06-24 14:12 UTC, pesublet commented on src/test/java/com/payline/payment/natixis/service/impl/WalletServiceImplTest.java
> +        Assertions.assertEquals(WalletCreateResponseFailure.class, response.getClass());
tester le contenu de l'objet !

2020-06-24 14:12 UTC, pesublet commented on src/test/java/com/payline/payment/natixis/service/impl/WalletServiceImplTest.java
> +        Assertions.assertEquals(1, response.getWalletFields().size());
tester le contenu de l'objet !

2020-07-07 15:59 UTC, JanFLORENT commented on src/main/java/com/payline/payment/natixis/service/GenericPaymentService.java
> +        NumberFormat nf = NumberFormat.getInstance(Locale.UK);
Oui, la methode format du NumberFormat nf affichera le chiffre avec une "," pour une locale FRENCH, ou un "." pour une locale ENGLISH.

Dans notre cas on veut un "."

2020-07-07 16:00 UTC, JanFLORENT commented on src/main/java/com/payline/payment/natixis/service/GenericPaymentService.java
> +        NumberFormat nf = NumberFormat.getInstance(Locale.UK);
il y a du y avoir un couac, c'est la meme remarque qu'au dessus.

2020-07-07 16:02 UTC, JanFLORENT commented on src/main/java/com/payline/payment/natixis/service/GenericPaymentService.java
> +        NumberFormat nf = NumberFormat.getInstance(Locale.UK);
j'ajoute un commentaire dans le code pour preciser ce choix

2020-07-07 16:16 UTC, JanFLORENT commented on src/main/java/com/payline/payment/natixis/service/GenericPaymentService.java
> +                builder.addAddressLine(PluginUtils.replaceChars(address.getStreet1() + " " + address.getStreet2()));
corrigé

2020-07-07 16:18 UTC, JanFLORENT commented on src/main/java/com/payline/payment/natixis/service/GenericPaymentService.java
> +            paymentResponse = e.toPaymentResponseFailureBuilder().build();
fait

2020-07-07 16:34 UTC, JanFLORENT commented on src/test/java/com/payline/payment/natixis/service/GenericPaymentServiceTest.java
> +        TestUtils.checkPaymentResponse( (PaymentResponseRedirect) paymentResponse );
fait, d'ailleurs ca m'a permis de corriger un bug, Merci!

2020-07-07 16:41 UTC, JanFLORENT commented on src/test/java/com/payline/payment/natixis/service/GenericPaymentServiceTest.java
> +        TestUtils.checkPaymentResponse( (PaymentResponseFailure) paymentResponse );
fait

2020-07-07 16:41 UTC, JanFLORENT commented on src/test/java/com/payline/payment/natixis/service/GenericPaymentServiceTest.java
> +        TestUtils.checkPaymentResponse( (PaymentResponseFailure) paymentResponse );
fait

2020-07-07 16:44 UTC, JanFLORENT commented on src/test/java/com/payline/payment/natixis/service/impl/PaymentWalletServiceImplTest.java
> +        assertEquals( PaymentResponseRedirect.class, paymentResponse.getClass() );
fait

2020-07-07 16:44 UTC, JanFLORENT commented on src/test/java/com/payline/payment/natixis/service/GenericPaymentServiceTest.java
> +        TestUtils.checkPaymentResponse( (PaymentResponseFailure) paymentResponse );
fait

2020-07-08 10:09 UTC, JanFLORENT commented on src/test/java/com/payline/payment/natixis/service/impl/PaymentWalletServiceImplTest.java
> +        assertEquals( PaymentResponseFailure.class, paymentResponse.getClass() );
fait

2020-07-08 10:13 UTC, JanFLORENT commented on src/test/java/com/payline/payment/natixis/service/impl/WalletServiceImplTest.java
> +        Assertions.assertEquals(WalletCreateResponseFailure.class, response.getClass());
fait

2020-07-08 10:31 UTC, JanFLORENT commented on src/test/java/com/payline/payment/natixis/service/impl/WalletServiceImplTest.java
> +        Assertions.assertEquals(WalletCreateResponseFailure.class, response.getClass());
fait

2020-07-08 10:34 UTC, JanFLORENT commented on src/test/java/com/payline/payment/natixis/service/impl/WalletServiceImplTest.java
> +        Assertions.assertEquals(1, response.getWalletFields().size());
fait

2020-07-15 09:25 UTC, merged